---
title: "Fifa_2010"
author: "Joanna Kuc"
date: "2022-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This stuff will be generated using only sdamr 
 
```{r}
library(sdamr)
data("fifa2010teams")
head(fifa2010teams)
summary(fifa2010teams)
mean(fifa2010teams$goals_for)
IQR(fifa2010teams$goals_for,type=1) #interquartile range
sample_var(fifa2010teams$goals_for) #sample variance
sample_mode(fifa2010teams$goals_for) #sample mode
hist(fifa2010teams$goals_for)
hist(fifa2010teams$goals_for,main="Histogram of points scored by teams in the FIFA 2010 World Cup", xlab="Goals for", breaks=20) #Here changing title and labels

```

This stuff will come from ggplot2. 
This is meant to have nicer plots than the previous one. 

``` {r}
library(ggplot2)
ggplot(fifa2010teams,aes(x=goals_for)) + geom_histogram()
ggplot(fifa2010teams,aes(x=goals_for)) + geom_histogram(bins=10, colour="black", fill='#8C8279') + xlab("Goals scored")
boxplot(fifa2010teams$goals_for)
ggplot(fifa2010teams,aes(y=goals_for)) + geom_boxplot()
ggplot(fifa2010teams,aes(x="",y=goals_for)) + geom_boxplot(width=.2) + xlab("")
plot(x=fifa2010teams$matches_played, y=fifa2010teams$goals_for)
ggplot(fifa2010teams, aes(x=matches_played, y=goals_for)) + geom_point()

```
Other types of plots now. 

``` {r}

set.seed(467)
plot_raincloud(data=fifa2010teams, y=goals_for)

```

